prj_dir: /opt/audit-svc
compose_network: ""
database: "{{ lookup('hashi_vault', 'secret=kv/data/mkhat/database') }}" 
db_user: "{{ database.db_user }}"
db_pass: "{{ database.db_pass }}"
db_name: "{{ database.db_name }}"
db_host: "{{ database.db_host }}"