services:
  backend:
    image: anestesia-tech.gitlab.yandexcloud.net:5050/mariakhat/audit-svc:latest
    restart: always
    volumes:
      - ./render:/render
    environment:
      APP_CONFIG: /render/config.yml
    stdin_open: true
    tty: true
    network_mode: host
    depends_on:
      vault:
        condition: service_healthy

  vault:
    image: hashicorp/vault
    container_name: vault-agent
    restart: on-failure
    volumes:
      - ./render:/render
      - ./config:/config
    cap_add:
      - IPC_LOCK
    command: 'vault agent -config /config/agent-config.hcl'
    healthcheck:
      test: "bash -c -f /render/config.yml"
      start_period: 1m
      retries: 3
      timeout: 1m

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - "./audit-svc.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - backend

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.4.0
    command: '--nginx.scrape-uri=http://nginx/status'
    ports:
      - 9113:9113
    depends_on:
      - nginx

volumes:
  render: