services:
  vault:
    image: hashicorp/vault
    container_name: vault
    restart: on-failure:10
    ports:
      - "8201:8201"
    environment:
      VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8201'
      VAULT_DEV_ROOT_TOKEN_ID: myroot
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-volume:/data
volumes:
  vault-volume: