services:
  backend:
    image: anestesia-tech.gitlab.yandexcloud.net:5050/mariakhat/audit-svc:latest
    restart: always
    hostname: backend
    environment:
      APP_POSTGRES__DSN: ${APP_POSTGRES__DSN}
    volumes:
      - ./config.yml:/opt/audit-svc/config.yml
    stdin_open: true
    entrypoint:
        - /bin/bash
        - -c
        - |
          migrate
          server
    tty: true
    ports:
      - 127.0.0.1:8080:8080

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - "/opt/audit-svc/audit-svc.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - backend

  postgres:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $DB_USER -d $DB_NAME'"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.4.0
    command: '--nginx.scrape-uri=http://nginx/status'
    ports:
      - 9113:9113
    depends_on:
      - nginx

volumes:
  pg_data: